SimpleBlog/Areas/Admin/ViewModels/Posts.cs
using SimpleBlog.Infrastructure;
using SimpleBlog.Models;
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;

namespace SimpleBlog.Areas.Admin.ViewModels
{
    public class PostsIndex
    {
        public PagedData<Post> Posts { get; set; }
    }

    public class PostsForm
    {
        public bool IsNew { get; set; }
        public int? PostId { get; set; }

        [Required, MaxLength(128)]
        public string Title { get; set; }

        [Required, MaxLength(128)]
        public string Slug { get; set; }

        [Required, DataType(DataType.MultilineText)]
        public string Content { get; set; }
    }
}

SimpleBlog/Models/Post.cs
using NHibernate.Mapping.ByCode;
using NHibernate.Mapping.ByCode.Conformist;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace SimpleBlog.Models
{
    public class Post
    {
        public virtual int Id { get; set; }
        public virtual User User { get; set; }
        public virtual string Title { get; set; }
        public virtual string Slug { get; set; }
        public virtual string Content { get; set; }

        public virtual DateTime CreatedAt { get; set; }
        public virtual DateTime? UpdatedAt { get; set; }
        public virtual DateTime? DeletedAt { get; set; }
        public virtual Boolean IsDeleted { get { return DeletedAt != null; } } //soft deletion
        public virtual IList<Tag> Tags { get; set; }
    }

    public class PostMap : ClassMapping<Post>
    {
        public PostMap()
        {
            Table("posts");
            Id(x => x.Id, x => x.Generator(Generators.Identity));


            ManyToOne(x => x.User, x =>
            {
                x.Column("user_id");
                x.NotNullable(true);
            });
            Property(x => x.Title, x => x.NotNullable(true));
            Property(x => x.Slug, x => x.NotNullable(true));
            Property(x => x.Content, x => x.NotNullable(true));

            Property(x => x.CreatedAt, x => {
                x.Column("created_at");
                x.NotNullable(true);
            });

            Property(x => x.UpdatedAt, x => x.Column("updated_at"));
            Property(x => x.DeletedAt, x => x.Column("deleted_at"));

            Bag(x => x.Tags, x => {
                x.Table("post_tags");
                x.Key(y => y.Column("post_id"));
            }, x => x.ManyToMany(y => y.Column("tag_id")));



        }
    }


}

SimpleBlog/Areas/Admin/Controllers/PostsController.cs
using NHibernate.Linq;
using SimpleBlog.Areas.Admin.ViewModels;
using SimpleBlog.Infrastructure;
using SimpleBlog.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace SimpleBlog.Areas.Admin.Controllers
{
    [Authorize(Roles ="admin")]
    [SelectedTabAttribute("posts")]
    public class PostsController : Controller
    {
        private const int PostPerPage = 10;
        public ActionResult Index(int page = 1)
        {
            int totalPostCount = Database.Session.Query<Post>().Count();

            var currentPostPage = Database.Session.Query<Post>()
                .OrderByDescending(c => c.CreatedAt)
                .Skip((page - 1) * PostPerPage)
                .Take(PostPerPage)
                .ToList();

            return View(new PostsIndex() { Posts = new PagedData<Post>(currentPostPage, totalPostCount, page, PostPerPage) });
        }

        public ActionResult New()
        {
            return View("Form", new PostsForm() { IsNew = true });
        }

        public ActionResult Edit(int id)
        {
            var post = Database.Session.Load<Post>(id);
            if (post == null)
            {
                return HttpNotFound();
            }


            return View("Form", new PostsForm() { IsNew = false, PostId = post.Id, Title = post.Title, Content = post.Content, Slug = post.Slug });
        }

        [HttpPost, ValidateInput(false)]
        public ActionResult Form(PostsForm form)
        {
            form.IsNew = form.PostId == null;

            if (!ModelState.IsValid)
                return View(form);

            Post post;

            if (form.IsNew)
            {
                post = new Post()
                {
                    Title = form.Title,
                    Slug = form.Slug,
                    Content = form.Content,
                    CreatedAt = DateTime.UtcNow,
                    User = Auth.User

                };
            }
            else
            {
                post = Database.Session.Load<Post>(form.PostId);

                if (post == null)
                {
                    return HttpNotFound();
                }

                post.Title = form.Title;
                post.Slug = form.Slug;
                post.Content = form.Content;
                post.UpdatedAt = DateTime.UtcNow;
            }

            Database.Session.SaveOrUpdate(post);

            Database.Session.Flush();
            return RedirectToAction("Index");
        }

        public ActionResult Trash(int id)
        {
            var post = Database.Session.Load<Post>(id);
            if (post == null)
                return HttpNotFound();
            post.DeletedAt = DateTime.UtcNow;
            Database.Session.Update(post);
            return RedirectToAction("index");
        }

        public ActionResult Delete(int id)
        {
            var post = Database.Session.Load<Post>(id);
            if (post == null)
                return HttpNotFound();

            Database.Session.Delete(post);
            return RedirectToAction("index");
        }

        public ActionResult Restore(int id)
        {
            var post = Database.Session.Load<Post>(id);
            if (post == null)
                return HttpNotFound();
            post.DeletedAt = null;
            Database.Session.Update(post);
            return RedirectToAction("index");
        }
    }
}

SimpleBlog/Controllers/PostsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace SimpleBlog.Controllers
{
    public class PostsController : Controller
    {
        // GET: Posts
        public ActionResult Index()
        {
            return View();
        }
    }
}

SimpleBlog/Areas/Admin/Views/Posts/Form.cshtml
@using System.Web.Optimization
@model SimpleBlog.Areas.Admin.ViewModels.PostsForm
<h1>@(Model.IsNew ? "Create Post" : "Update Post")</h1>
@using (Html.BeginForm("Form", "Posts"))
{
    if (!Model.IsNew)
    {
        @Html.HiddenFor(p => p.PostId)
    }

    <div class="row">
        <div class="col-lg-8">
            @Html.ValidationSummary()
            <div class="form-group">
                @Html.LabelFor(f => f.Title)
                @Html.TextBoxFor(f => f.Title, new { @class = "form-control" })
            </div>

            <div class="form-group">
                @Html.LabelFor(f => f.Slug)
                @Html.TextBoxFor(f => f.Slug, new { @class = "form-control", data_slug = "#Title" })
            </div>
            <div class="form-group">
                @Html.LabelFor(f => f.Content)
                @Html.TextAreaFor(f => f.Content, new { @class = "form-control" })
            </div>
        </div>
        <div class="col-lg-4">
            <div class="panel panel-info">
                <div class="panel-heading">Post Actions</div>
                <div class="panel-body">
                    <input type="submit" value="@(Model.IsNew?"Publish Post":"Update Post")" class="btn btn-success btn-sm" />
                    <a href="@Url.Action("index")"> or cancel</a>
                </div>
            </div>
        </div>
    </div>



    @section Scripts{
        @Scripts.Render("~/admin/posts/scripts")
        <script src="~/Scripts/ckeditor/ckeditor.js"></script>
        <script>
                CKEDITOR.replace("Content");
        </script>
    }
}

SimpleBlog/Areas/Admin/Views/Posts/Index.cshtml
@model SimpleBlog.Areas.Admin.ViewModels.PostsIndex
<h1>Posts</h1>
<div class="btn-toolbar">
    <div class="btn-group">
        <a href="@Url.Action("new")" class="btn btn-primary btn-sm"><i class="glyphicon glyphicon-plus"></i>Create Post</a>
    </div>
    <div class="btn-group pull-right">
        @if (Model.Posts.HasPreviousPage)
        {
            <a href="@Url.Action("index",new { page=Model.Posts.PreviousPage})" class="btn btn-primary btn-sm">
                <i class="glyphicon glyphicon-chevron-left"></i>
                Previous Page
            </a>
        }
        else
        {
            <a href="#" class="btn btn-default disabled btn-sm">
                <i class="glyphicon glyphicon-chevron-left"></i>
                Previous Page
            </a>
        }
        @if (Model.Posts.HasNextPage)
        {
            <a href="@Url.Action("index",new { page=Model.Posts.NextPage})" class="btn btn-primary btn-sm">

                Next Page <i class="glyphicon glyphicon-chevron-right"></i>
            </a>
        }
        else
        {
            <a href="#" class="btn btn-default disabled btn-sm">

                Next Page <i class="glyphicon glyphicon-chevron-right"></i>
            </a>
        }
    </div>
    <table class="table table-striped">
        <thead>
            <tr>
                <th>Title</th>
                <th>Author</th>
                @*<th>Tags</th>*@
                <th>Date</th>
                <th>Actions</th>
            </tr>
        </thead>
        <tbody>
            @foreach (var post in Model.Posts)
            {
                var cls = "";
                if (post.IsDeleted)
                {
                    cls = "danger";
                }


                <tr class="@cls">
                    <td>@post.Title</td>
                    <td>@post.User.Username</td>
                    @*<td>@string.Join(", ", post.Tags.Select(p => p.Name))</td>*@
                    <td>@post.CreatedAt</td>
                    <td>

                        @if (!post.IsDeleted)
                        {
                            <div class="btn-group btn-group-xs">
                                <a href="@Url.Action("edit",new {post.Id })" class="btn btn-primary btn-xs"><i class="glyphicon glyphicon-edit"></i>Edit</a>
                                <a href="@Url.Action("trash", new { post.Id })" class="btn btn-danger"><i class="glyphicon glyphicon-remove"></i>Trash</a>

                                <a href="@Url.Action("delete", new { post.Id })" class="btn btn-danger dropdown-toggle" data-toggle="dropdown"><span class="caret"></span></a>
                                <ul class="dropdown-menu">
                                    <li>
                                        <a href="@Url.Action("delete",new { post.Id})"><i class="glyphicon glyphicon-remove"></i>delete</a>
                                    </li>
                                </ul>

                            </div>
                        }
                        else
                        {
                            <a href="@Url.Action("restore",new { post.Id})" class="btn btn-xs btn-success">
                                <i class="glyphicon glyphicon-plus-sign"></i>
                                Restore
                            </a>
                        }
                    </td>
                </tr>
            }
        </tbody>
    </table>
</div>